### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#This will create this metric in all the tiers, under this path
#metricPrefix: Custom Metrics|SonicMq|

#This will create it in specific Tier. Replace <TIER_NAME>. If TIER_NAME is not specified, the extension will
# also try to get the tierName from the JVM argument.
metricPrefix: Server|Component:<TIER_NAME>|Custom Metrics|SonicMq


#location for eg. tcp://localhost:2506
location: ""

username: ""

password: ""

brokers:
  - displayName: ""
    objectName: ""
    container:
        objectName: ""
        displayName: ""

  - displayName: ""
    objectName: ""
    container:
        objectName: ""
        displayName: ""


#JMX timeout in seconds
timeout: 30

#Comma Separated Regex patterns to exclude queues.
queueExcludePatterns: [

]

#Comma Separated Regex patterns to exclude users.
userExcludePatterns: [

]

#Comma Separated Regex patterns to exclude durable subscriptions.
topicExcludePatterns: [

]
